-- 003_rutinas_y_ejercicios.sql
--
-- Fase 4: dominio entrenador↔cliente. Tablas de contenido: un ENTRENADOR
-- crea rutinas (secuencias de ejercicios) y luego las asigna a los CLIENTES
-- con los que tiene un acompañamiento activo (ver 004).
--
-- En desarrollo local el esquema lo crea Hibernate (DDL_AUTO=update); este
-- script es para entornos donde se maneja el esquema a mano (prod/CI).
--
-- CÓMO APLICAR:
--   1. Verificar que los nombres de tabla/columnas coincidan con los
--      modelos JPA (rutinas.entrenador_id, ejercicios.rutina_id).
--   2. Backup antes de correrlo en entornos con datos reales
--      (ver docs/BACKUP_RUNBOOK.md).
--   3. Este script es aditivo (CREATE TABLE ... IF NOT EXISTS): se puede
--      correr con el servidor abajo o arriba sin destruir datos.

CREATE TABLE IF NOT EXISTS rutinas (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    entrenador_id BIGINT       NOT NULL REFERENCES usuarios (id),
    nombre        VARCHAR(120) NOT NULL,
    descripcion   VARCHAR(500),
    activo        BOOLEAN      NOT NULL DEFAULT TRUE,
    creado_en     TIMESTAMP,
    version       BIGINT
);

CREATE TABLE IF NOT EXISTS ejercicios (
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    rutina_id    BIGINT       NOT NULL REFERENCES rutinas (id) ON DELETE CASCADE,
    nombre       VARCHAR(120) NOT NULL,
    series       INTEGER      NOT NULL CHECK (series >= 1),
    repeticiones INTEGER      NOT NULL CHECK (repeticiones >= 1),
    orden        INTEGER      NOT NULL CHECK (orden >= 1)
);

-- Las rutinas se listan por entrenador (creador); el acceso de escritura es
-- del creador (chequeo de ownership en RutinaService, no solo esta PK).
CREATE INDEX IF NOT EXISTS idx_rutinas_entrenador ON rutinas (entrenador_id);

-- Los ejercicios siempre se leen junto con su rutina, ordenados por orden.
CREATE INDEX IF NOT EXISTS idx_ejercicios_rutina ON ejercicios (rutina_id, orden);
