-- 004_asignaciones_entrenador_y_rutina.sql
--
-- Fase 4: dominio entrenador↔cliente. Tablas de relación:
--   - asignaciones_entrenador: un ENTRENADOR se asigna como acompañante de
--     un CLIENTE cuyo plan activo incluye entrenador personal (regla
--     evaluada en EntrenadorService; el cliente solo puede tener UNA
--     asignación ACTIVA — de ahí el índice único parcial, mismo patrón que
--     001 para suscripciones ACTIVA).
--   - asignaciones_rutina: una rutina creada por el entrenador se asigna a
--     un cliente acompañado. Un cliente puede tener la misma rutina
--     asignada solo una vez (unique simple).
--
-- En desarrollo local el esquema lo crea Hibernate (DDL_AUTO=update); este
-- script es para entornos donde se maneja el esquema a mano (prod/CI).
--
-- CÓMO APLICAR:
--   1. Verificar que los nombres de tabla/columnas coincidan con los
--      modelos JPA.
--   2. Backup antes de correrlo en entornos con datos reales.
--   3. Aditivo (IF NOT EXISTS): no destruye datos.

CREATE TABLE IF NOT EXISTS asignaciones_entrenador (
    id            BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id    BIGINT  NOT NULL REFERENCES usuarios (id),
    entrenador_id BIGINT  NOT NULL REFERENCES usuarios (id),
    activa        BOOLEAN NOT NULL DEFAULT TRUE,
    asignado_en   TIMESTAMP,
    version       BIGINT
);

CREATE TABLE IF NOT EXISTS asignaciones_rutina (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    cliente_id  BIGINT   NOT NULL REFERENCES usuarios (id),
    rutina_id   BIGINT   NOT NULL REFERENCES rutinas (id) ON DELETE CASCADE,
    asignado_en TIMESTAMP,
    CONSTRAINT uq_asignacion_rutina UNIQUE (cliente_id, rutina_id)
);

-- Índice único parcial: como mucho UNA asignación de entrenador ACTIVA por
-- cliente (puede haber varias inactivas a lo largo del tiempo = historial de
-- acompañantes). Es la red de seguridad de integridad a nivel BD para el
-- chequeo check-then-act de EntrenadorService.asignarme(), igual que 001
-- para las suscripciones ACTIVA.
CREATE UNIQUE INDEX IF NOT EXISTS uq_acompanante_activo_por_cliente
    ON asignaciones_entrenador (cliente_id)
    WHERE activa = TRUE;

-- El entrenador lista a sus acompañados (para asignar rutinas); el servicio
-- además filtra por entrenador_id en Java.
CREATE INDEX IF NOT EXISTS idx_asignaciones_entrenador_entrenador
    ON asignaciones_entrenador (entrenador_id) WHERE activa = TRUE;

CREATE INDEX IF NOT EXISTS idx_asignaciones_rutina_cliente
    ON asignaciones_rutina (cliente_id);

-- Verificación rápida post-aplicación:
-- SELECT cliente_id, COUNT(*) FROM asignaciones_entrenador
-- WHERE activa = TRUE GROUP BY cliente_id HAVING COUNT(*) > 1;
