-- 005_codigo_carnet_y_asistencias.sql
--
-- Fase 5: carnet digital + dominio de asistencias/check-in.
--
-- 1) usuarios.codigo_carnet: código corto (6-8 chars) de acceso tipo carnet,
--    generado en AuthService.registrar (CodigoCarnetGenerator.java, P3). El
--    backfill de abajo genera los códigos de los usuarios existentes y de los
--    que queden sin código (idempotente: solo toca NULLs). La rotación por
--    pérdida y el "generar on-demand" viven en UsuarioService (P3) y usan el
--    MISMO alfabeto que este literal.
--
--    ALFABETO (literal compartido — debe coincidir SIEMPRE con el de
--    CodigoCarnetGenerator.java): sin 0/O/1/I para evitar ambigüedad visual.
--    24 letras (A-Z sin I ni O) + 8 dígitos (2-9) = 32 símbolos. Longitud
--    del backfill: 8 (dentro del rango 6-8 del generador Java).
--
-- 2) asistencias: entrada por día por usuario con índice único (usuario_id,
--    fecha) — red de seguridad del chequeo check-then-act de
--    AsistenciaService (regla 1/día). Como en la entidad Asistencia
--    (@UniqueConstraint llamado uq_asistencia_por_dia) co-existen sin
--    conflicto: en Postgres la constraint y su índice comparten nombre.
--
-- En desarrollo local el esquema lo crea Hibernate (DDL_AUTO=update); este
-- script es para entornos donde se maneja el esquema a mano (prod/CI) y para
-- el backfill de carnet, que Hibernate no hace.
--
-- CÓMO APLICAR:
--   1. Backup antes de correrlo en entornos con datos reales
--      (ver docs/BACKUP_RUNBOOK.md).
--   2. Aditivo e idempotente (IF NOT EXISTS / WHERE codigo_carnet IS NULL):
--      se puede correr con el servidor abajo o arriba sin destruir datos.
--   3. Correr contra dev primero y verificar (ver "Verificación rápida").

ALTER TABLE usuarios ADD COLUMN IF NOT EXISTS codigo_carnet VARCHAR(8);

-- Backfill: genera código a los usuarios que no tienen (idempotente, retry
-- de colisión respaldado por el índice único parcial de abajo). Si un UPDATE
-- choca con el índice, se reintenta hasta 10 veces; si agota la colisión,
-- falla el script (gating estricto, misma política que CodigoCarnetGenerator).
DO $$
DECLARE
    alfabeto CONSTANT TEXT := 'ABCDEFGHJKLMNPQRSTUVWXYZ23456789';
    u RECORD;
    nuevo_codigo TEXT;
    intentos INT;
BEGIN
    FOR u IN SELECT id FROM usuarios WHERE codigo_carnet IS NULL LOOP
        intentos := 0;
        LOOP
            intentos := intentos + 1;
            nuevo_codigo := '';
            FOR i IN 1..8 LOOP
                nuevo_codigo := nuevo_codigo
                    || substr(alfabeto, 1 + floor(random() * 32)::int, 1);
            END LOOP;
            BEGIN
                UPDATE usuarios SET codigo_carnet = nuevo_codigo WHERE id = u.id;
                EXIT; -- update exitoso, sin colisión
            EXCEPTION WHEN unique_violation THEN
                IF intentos >= 10 THEN
                    RAISE EXCEPTION 'no se pudo generar codigo_carnet único para usuario %',
                        u.id;
                END IF;
            END;
        END LOOP;
    END LOOP;
END $$;

-- Índice único parcial: un usuario sin código (NULL) no participa; el gating
-- de AuthService garantiza que en la práctica nunca se guarde un usuario sin
-- código. Patrón: 004:44-46.
CREATE UNIQUE INDEX IF NOT EXISTS uq_usuarios_codigo_carnet
    ON usuarios (codigo_carnet)
    WHERE codigo_carnet IS NOT NULL;

-- Tabla de asistencias (check-in). entrada_en se llena al crear (PrePersist
-- de la entidad); salida_en queda reservado para el check-out (backlog).
CREATE TABLE IF NOT EXISTS asistencias (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    usuario_id  BIGINT    NOT NULL REFERENCES usuarios (id),
    fecha       DATE      NOT NULL,
    entrada_en  TIMESTAMP,
    salida_en   TIMESTAMP,
    metodo      VARCHAR
);

-- Red de seguridad de la carrera 1/día a nivel BD (mismo nombre que el
-- @UniqueConstraint de Asistencia.java, para que no haya divergencia con
-- DDL_AUTO=validate).
CREATE UNIQUE INDEX IF NOT EXISTS uq_asistencia_por_dia
    ON asistencias (usuario_id, fecha);

-- Stats agrupadas por fecha (DashboardAdminService, Fase 5).
CREATE INDEX IF NOT EXISTS idx_asistencias_fecha
    ON asistencias (fecha);

-- Verificación rápida post-aplicación:
-- SELECT COUNT(*) FROM usuarios WHERE codigo_carnet IS NULL;          -- debe dar 0
-- SELECT indexname FROM pg_indexes WHERE tablename = 'usuarios'
--   AND indexname = 'uq_usuarios_codigo_carnet';                      -- debe existir
-- SELECT indexname FROM pg_indexes WHERE tablename = 'asistencias';   -- uq_asistencia_por_dia + idx_asistencias_fecha
-- SELECT usuario_id FROM suscripciones
--   WHERE estado = 'ACTIVA'
--   GROUP BY usuario_id HAVING COUNT(*) > 1;                          -- verificación de 001: 0 filas